export default {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_REDIRECT: 'LOGIN_REDIRECT',

    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_ERROR: 'REGISTER_ERROR',
    REGISTER_FAILED: 'REGISTER_FAILED',

    FETCH_VEHICLE_REQUEST: 'FETCH_VEHICLE_REQUEST',
    FETCH_VEHICLE_GUEST_REQUEST: 'FETCH_VEHICLE_GUEST_REQUEST',
    FETCH_VEHICLE_SUCCESS: 'FETCH_VEHICLE_SUCCESS',
    FETCH_VEHICLE_ERROR: 'FETCH_VEHICLE_ERROR',
    FETCH_VEHICLE_LOADING: 'FETCH_VEHICLE_ERROR'
}